import { Course } from '@/lib/validations/course';
import { Quiz, QuizVersion } from '@/lib/validations/quiz';
import { Attempt, StudentResponse } from '@/lib/validations/attempt';
import sampleBank from '@/examples/os-question-bank.json';

export const SEED_COURSE: Course = {
  id: 'course-cse307-spring2026',
  courseCode: 'CSE-307',
  courseTitle: 'Operating System',
  semester: 'Spring 2026',
  academicYear: '2025-2026',
  institution: 'Department of Computer Science & Engineering',
  description: 'Undergraduate core course covering process management, virtual memory architectures, file systems, and I/O scheduling.',
  instructorIds: ['demo-instructor-turing'],
  enrollmentCode: 'OS2026',
  sections: [
    { id: 'sec-a', name: 'Section A', studentIds: ['demo-student-ada'] },
    { id: 'sec-b', name: 'Section B', studentIds: ['demo-student-linus'] },
  ],
  isArchived: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const SEED_QUESTIONS = sampleBank.questions as any[];

export const SEED_QUIZ_ASSESSMENT: Quiz = {
  id: 'quiz-vm-assessment',
  courseId: SEED_COURSE.id,
  title: 'Assessment 1: Virtual Memory & Address Translation',
  description: 'Graded mid-term assessment on Paging, TLB, Page Fault handling, and Address Translation.',
  instructions: 'Please answer all questions. You will have 30 minutes once started. Your responses autosave continuously. Solutions are released after deadline.',
  assignedSectionIds: [], // all sections
  mode: 'assessment',
  availableFrom: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
  dueAt: new Date(Date.now() + 3600 * 1000 * 72).toISOString(),
  timeLimitMinutes: 30,
  maxAttempts: 1,
  shuffleQuestions: false,
  shuffleOptions: true,
  immediateFeedback: false,
  revealCorrectAnswer: false,
  revealExplanation: false,
  showScoreImmediately: false,
  collectConfidence: true,
  isPublished: true,
  activeVersionId: 'ver-quiz-vm-v1',
  questionIds: ['q-bank-01', 'q-bank-02', 'q-bank-03', 'q-bank-04', 'q-bank-05', 'q-bank-06', 'q-bank-11'],
  createdBy: 'demo-instructor-turing',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const SEED_QUIZ_VERSION_ASSESSMENT: QuizVersion = {
  id: 'ver-quiz-vm-v1',
  quizId: SEED_QUIZ_ASSESSMENT.id,
  versionNumber: 1,
  publishedAt: new Date().toISOString(),
  publishedBy: 'demo-instructor-turing',
  questions: SEED_QUESTIONS.filter(q => SEED_QUIZ_ASSESSMENT.questionIds.includes(q.id)),
  totalPoints: 19,
  mode: 'assessment',
  timeLimitMinutes: 30,
  collectConfidence: true,
  immediateFeedback: false,
  revealCorrectAnswer: false,
  revealExplanation: false,
  showScoreImmediately: false,
};

export const SEED_QUIZ_PRACTICE: Quiz = {
  id: 'quiz-disk-practice',
  courseId: SEED_COURSE.id,
  title: 'Interactive Practice: Disk Head Scheduling',
  description: 'Self-paced simulation activity to test and compare FCFS, SSTF, SCAN, and C-SCAN scheduling.',
  instructions: 'Practice mode with immediate feedback. Inspect the horizontal cylinder track, predict head trajectory, and review step-by-step explanations.',
  assignedSectionIds: [],
  mode: 'practice',
  availableFrom: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
  dueAt: new Date(Date.now() + 3600 * 1000 * 168).toISOString(),
  timeLimitMinutes: 0,
  maxAttempts: 0, // unlimited
  shuffleQuestions: false,
  shuffleOptions: false,
  immediateFeedback: true,
  revealCorrectAnswer: true,
  revealExplanation: true,
  showScoreImmediately: true,
  collectConfidence: true,
  isPublished: true,
  activeVersionId: 'ver-quiz-disk-v1',
  questionIds: ['q-bank-07', 'q-bank-08', 'q-bank-10', 'q-bank-12'],
  createdBy: 'demo-instructor-turing',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const SEED_QUIZ_VERSION_PRACTICE: QuizVersion = {
  id: 'ver-quiz-disk-v1',
  quizId: SEED_QUIZ_PRACTICE.id,
  versionNumber: 1,
  publishedAt: new Date().toISOString(),
  publishedBy: 'demo-instructor-turing',
  questions: SEED_QUESTIONS.filter(q => SEED_QUIZ_PRACTICE.questionIds.includes(q.id)),
  totalPoints: 11,
  mode: 'practice',
  collectConfidence: true,
  immediateFeedback: true,
  revealCorrectAnswer: true,
  revealExplanation: true,
  showScoreImmediately: true,
};

// Realistic mock attempts for rich analytics preview
export const SEED_ATTEMPTS: Attempt[] = [
  {
    id: 'att-ada-01',
    userId: 'demo-student-ada',
    userName: 'Ada Lovelace',
    userEmail: 'ada.lovelace@student.edu',
    courseId: SEED_COURSE.id,
    quizId: SEED_QUIZ_ASSESSMENT.id,
    quizVersionId: SEED_QUIZ_VERSION_ASSESSMENT.id,
    attemptNumber: 1,
    startedAt: new Date(Date.now() - 3600 * 1000 * 3).toISOString(),
    submittedAt: new Date(Date.now() - 3600 * 1000 * 2.5).toISOString(),
    status: 'submitted',
    score: 19,
    maxScore: 19,
    percentage: 100,
  },
  {
    id: 'att-linus-01',
    userId: 'demo-student-linus',
    userName: 'Linus Torvalds',
    userEmail: 'linus.torvalds@student.edu',
    courseId: SEED_COURSE.id,
    quizId: SEED_QUIZ_ASSESSMENT.id,
    quizVersionId: SEED_QUIZ_VERSION_ASSESSMENT.id,
    attemptNumber: 1,
    startedAt: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
    submittedAt: new Date(Date.now() - 3600 * 1000 * 4.6).toISOString(),
    status: 'submitted',
    score: 15,
    maxScore: 19,
    percentage: 79,
  },
  {
    id: 'att-curie-01',
    userId: 'demo-student-curie',
    userName: 'Marie Curie',
    userEmail: 'marie.curie@student.edu',
    courseId: SEED_COURSE.id,
    quizId: SEED_QUIZ_ASSESSMENT.id,
    quizVersionId: SEED_QUIZ_VERSION_ASSESSMENT.id,
    attemptNumber: 1,
    startedAt: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    submittedAt: new Date(Date.now() - 3600 * 1000 * 5.4).toISOString(),
    status: 'submitted',
    score: 17,
    maxScore: 19,
    percentage: 89,
  },
  {
    id: 'att-hopper-01',
    userId: 'demo-student-hopper',
    userName: 'Grace Hopper',
    userEmail: 'grace.hopper@student.edu',
    courseId: SEED_COURSE.id,
    quizId: SEED_QUIZ_ASSESSMENT.id,
    quizVersionId: SEED_QUIZ_VERSION_ASSESSMENT.id,
    attemptNumber: 1,
    startedAt: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
    submittedAt: new Date(Date.now() - 3600 * 1000 * 7.5).toISOString(),
    status: 'submitted',
    score: 18,
    maxScore: 19,
    percentage: 95,
  },
];

export const SEED_RESPONSES: Record<string, StudentResponse[]> = {
  'att-ada-01': [
    {
      questionId: 'q-bank-01',
      attemptId: 'att-ada-01',
      userId: 'demo-student-ada',
      answer: 'opt-2',
      isCorrect: true,
      pointsEarned: 2,
      responseTimeMs: 14200,
      confidenceRating: 5,
      hintUsed: false,
      changedAnswerCount: 0,
      updatedAt: new Date().toISOString(),
    },
    {
      questionId: 'q-bank-03',
      attemptId: 'att-ada-01',
      userId: 'demo-student-ada',
      answer: 140,
      isCorrect: true,
      pointsEarned: 4,
      responseTimeMs: 28500,
      confidenceRating: 5,
      hintUsed: false,
      changedAnswerCount: 0,
      updatedAt: new Date().toISOString(),
    },
    {
      questionId: 'q-bank-06',
      attemptId: 'att-ada-01',
      userId: 'demo-student-ada',
      answer: {
        logicalAddressBinary: '11',
        pageNumber: 1,
        pageOffset: 1,
        frameNumber: 4,
        physicalAddressBinary: '1001',
        physicalAddressDecimal: 9,
      },
      isCorrect: true,
      pointsEarned: 5,
      responseTimeMs: 45000,
      confidenceRating: 5,
      hintUsed: false,
      changedAnswerCount: 0,
      updatedAt: new Date().toISOString(),
    },
  ],
  'att-linus-01': [
    {
      questionId: 'q-bank-01',
      attemptId: 'att-linus-01',
      userId: 'demo-student-linus',
      answer: 'opt-2',
      isCorrect: true,
      pointsEarned: 2,
      responseTimeMs: 18000,
      confidenceRating: 4,
      hintUsed: false,
      changedAnswerCount: 1,
      updatedAt: new Date().toISOString(),
    },
    {
      questionId: 'q-bank-03',
      attemptId: 'att-linus-01',
      userId: 'demo-student-linus',
      answer: 120, // wrong
      isCorrect: false,
      pointsEarned: 0,
      responseTimeMs: 32000,
      confidenceRating: 2,
      hintUsed: false,
      changedAnswerCount: 2,
      updatedAt: new Date().toISOString(),
    },
    {
      questionId: 'q-bank-06',
      attemptId: 'att-linus-01',
      userId: 'demo-student-linus',
      answer: {
        logicalAddressBinary: '11',
        pageNumber: 1,
        pageOffset: 1,
        frameNumber: 4,
        physicalAddressBinary: '1001',
        physicalAddressDecimal: 9,
      },
      isCorrect: true,
      pointsEarned: 5,
      responseTimeMs: 52000,
      confidenceRating: 4,
      hintUsed: false,
      changedAnswerCount: 0,
      updatedAt: new Date().toISOString(),
    },
  ],
};
